import type { Metadata, Viewport } from "next";
import { Roboto } from "next/font/google";

import Wrapper from "@/src/contextProviders/Wrapper";
import ThemeProvider from "@/src/libs/ThemeProvider";

import "./globals.css";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--roboto-font",
});

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#000000" },
  ],
};

export const metadata: Metadata = {
  title: "Basic Next.js Blog Project",
  description: "Generated by Mahir Saleh",

  manifest: "/app/manifest.ts",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "My Blog",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <Wrapper>{children}</Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
