import type { Metadata } from "next";
import { Roboto } from "next/font/google";

// import { Suspense } from "react";

import Wrapper from "@/src/contextProviders/Wrapper";
import ThemeProvider from "@/src/libs/ThemeProvider";
// import AuthWrapper from "@/src/contextProviders/AuthWrapper";

// import convex with better-auth ;

import "./globals.css";
// import Loading from "./loading";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--roboto-font",
});

export const metadata: Metadata = {
  title: "Basic Next.js Blog Project",
  description: "Generated by Mahir Saleh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <Wrapper>
            {children}
          </Wrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
